module.exports = {
    BASE_URL: 'http://localhost:8080/api/',
    REPRESENTATIVE: 'representative/',
    CUSTOMER: 'customer/',
    CONSULTANT: 'consultant/',
    COMPANY: 'company/',
    PRODUCT: 'product/',
    ORDER: 'order/',
    CONSULTATION: 'consultation/',
    CERTIFICATE: 'certificate/',
    GET: 'list/',
    PUT: 'list/',
    PATCH: 'list/',
    POST: '',
    DELETE: 'list/',
    AUTHENTICATE: 'authenticate',
    IMPORT: 'import/',
    IMPORT_CONFIG: 'importConfig/',
    BATCH_DELETE: 'batchDelete/',
    CHAT: 'chat/'
}