
module.exports = {
    HOST: 'remote-consultant.herokuapp.com',
    // HOST: 'localhost',
    BASE_URL: 'https://remote-consultant.herokuapp.com/api/',
    // BASE_URL: 'http://localhost:8080/api/',
    PORT: '443',
    // PORT: '8080',
    SECURE: true,
    // SECURE: false,
    REPRESENTATIVE: 'representative/',
    CUSTOMER: 'customer/',
    CONSULTANT: 'consultant/',
    COMPANY: 'company/',
    PRODUCT: 'product/',
    ORDER: 'order/',
    CONSULTATION: 'consultation/',
    CERTIFICATE: 'certificate/',
    GET: 'list/',
    PUT: 'list/',
    PATCH: 'list/',
    POST: '',
    DELETE: 'list/',
    AUTHENTICATE: 'authenticate',
    IMPORT: 'import/',
    IMPORT_CONFIG: 'importConfig/',
    REQUEST: '/request/',
    BATCH_DELETE: 'batchDelete/',
    CHAT: 'chat/',
}